# 本文件是配置备份，防止spring cloud config配置中心服务无法使用
server:
  port: 7001
spring:
  application:
    name: ServiceA
  thymeleaf:
    encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #表示不返回时间戳，如果为true返回时间戳，如果这三行同时存在，以第三行为准即返回时间戳
      write-dates-as-timestamps: false
  aop:
    auto: true
  ########################### 数据源配置 ####################################
  druid:
    url: jdbc:mysql://192.168.10.99:3306/cloudengine?userUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
    username: ce_admin
    password: abc123
    driverClassName: com.mysql.jdbc.Driver
    #池启动时创建的链接数量
    initialSize: 5
    #最小空闲链接数量
    minIdle: 5
    #同一时间可以从池分配的最多连接数量。设置为0时表示无限制
    maxActive: 50
    #在抛出异常之前，池等待连接被回收的最长时间（当没有连接可用时），设置为-1时表示无限制等待
    maxWait: 10000
    #检查一次连接池中空闲的连接
    timeBetweenEvictionRunsMillis: 60000
    #连接保持空闲而不被驱逐的最长时间
    minEvictableIdleTimeMillis: 300000
    #测试连接状态
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    #超过时间限制是否回收
    removeAbandoned: true
    #超时时间：单位为秒
    removeAbandonedTimeout: 180
  #Redis单机版
  redis:
    database: 0
    host: 192.168.122.108
    password: abc123
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    #Redis集群版
    #  redis:
    #    timeout: 6000ms
    #    database: 0
    #    cluster:
    #      nodes:
    #        - 192.168.10.99:6379
    #        - 192.168.10.99:6380
    #        - 192.168.10.99:6381
    #        - 192.168.10.99:6382
    #        - 192.168.10.99:6383
    #        - 192.168.10.99:6384
    #      max-redirects: 3 #获取失败最大重定向次数
    #    lettuce:
    #      pool:
    #        max-active: 1000 #连接池最大连接数(使用负数表示没有限制)
    #        max-idle: 10 #连接池最大空闲连接
    #        max-wait: -1ms #连接池最大阻塞等待时间(使用负数表示没有限制)
    #        min-idle: 0 #连接池最小空闲连接
    #      shutdown-timeout: 100ms
    #网关配置
#  cloud:
#    gateway:
#      routes:
#        - id: r1
#          uri: lb://servicea
#          predicates:
#            - Path=/api1/**
#          filters:
#            - RewritePath=/api1/(?<remaining>.*),/$\{remaining}
#            - AddResponseHeader=X-Response-Default-Foo,Default-Bar
#        - id: r2
#          uri: lb://MANOEUVRE
#          predicates:
#            - Path=/api2/**
#          filters:
#            - RewritePath=/api2/(?<remaining>.*),/$\{remaining}
#            - AddResponseHeader=X-Response-Default-Foo,Default-Bar

# eureka客户端
eureka:
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.application.name}@${eureka.instance.ip-address}@${server.port} #服务实例ID
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://jenkins.ce:6001/eureka/,http://jenkins.ce:6002/eureka/,http://jenkins.ce:6003/eureka/ #多个注册中心以逗号, 隔开
    registry-fetch-interval-seconds: 5

# eureka服务端
#eureka:
#  instance:
#    hostname: 192.168.10.99
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    wait-time-in-ms-when-sync-empty: 0
#    enable-self-preservation: false

## FTP文件服务器配置参数
ftp:
#  serverIp: ftp.ce
#  serverPort: 21
#  userId: apply
#  password: abc123
#  uploadPath: /upload/ # 若是上传到本地服务器，可以设置路径：D:\upload\files\
  #
  host: ftp.ce  #FTP 服务器 ip
  port: 21
  userName: apply
  passWord: abc123
  root: /
  workDirs: /upload/
  maxTotal: 100
  minIdle: 2
  maxIdle: 5
  maxWaitMillis: 3000
  uploadFlag: FTP_UPLOAD # LOCAL_UPLOAD 上传到本地服务器

management:
  endpoints:
    #    conditions:
    #      enabled: true
    health:
      sensitive: false #关闭过滤敏感信息
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

beetl-beetlsql:
  dev: true #默认是true,向控制台输出执行时候的sql，参数，执行时间，以及执行的位置，每次修改sql文件的时候，自动检测sql文件修改
beetlsql:
  sqlPath: /sql
  basePackage: com.hjyd
  daoSuffix: Dao #默认为Dao

logging:
  #  pattern:
  #    console: "%d - %msg%n"
  file: /tmp/logs/${spring.application.name}/${server.port}/log.log #日志记录文件存放位置，上线时修改为服务器的绝对路径 /usr/log
  #  path: logs\
  level:
    com.hjyd: error